[project]
name = "tuyawizard"
version = "0.1.8"
description = "Interactive wizard for Tuya Library"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [{name = "3735943886"}]
dependencies = [
  "qrcode",
  "tuya-device-sharing-sdk"
]

[project.urls]
Homepage = "https://github.com/3735943886/tuyawizard"

[project.scripts]
tuyawizard = "tuyawizard.__main__:main"

[tool.setuptools]
packages = ["tuyawizard"]
